config/routes.rb
Rails.application.routes.draw do
  get 'request_payments/index'
  get 'request_payments/new'
  get 'messages/index'
  get 'messages/show'
  devise_for :studio_owners, controllers: {
    sessions: 'studio_owners/sessions'
  }

  # Can add registrations: 'admin/registrations'
  #
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'dashboard#home'

  namespace :users do
    root 'users#dashboard'


  end

  namespace :studio_owners do
    root 'studio_owners#dashboard'
    get 'dashboard', to: 'studio_owners#dashboard'
    resources :student_management, only: [:index]
    resources :request_payments, only: [:index, :new]
    resource :account_management, only: [:edit, :index], controller: 'account_management' do
      post :accept_tos, on: :collection
    end
  end

  post '/create-checkout-session', to:'payments#payment_request' do
    content_type 'application/json'
  end

  get '/payment_success', to:'payments#success'
  get '/payment_failure', to:'payments#failure'




  # get 'users/signup', to: 'users/users#signup'
  post 'send_invitation', to: 'invitations#send_invitation'

  # get 'users/dashboard', to: 'users#dashboard', as: 'users_dashboard'
  # get 'studio_owners/dashboard', to: 'studio_owners#dashboard', as: 'studio_owners_dashboard'

  resources :studios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!, only: [:users]
  before_action :authenticate_studio_owner!, only: [:studio_owners]
  before_action :check_studio, only: [:studio_owners]
  before_action :check_user_type

  def home
    # If the current users type is a studio owner, redirect to the appropriate page.
    if current_studio_owner
      redirect_to studio_owners_root_path
    elsif current_user
      redirect_to users_root_path
    end
  end

  def users
  end

  def studio_owners
  end

  def check_studio
    unless current_studio_owner.studio
      # Redirect to the studio creation path
      # Replace 'new_studio_path' with the correct path for your application
      redirect_to new_studio_path
    end
    # No need for an 'if' block since you're only handling the case where the studio does not exist
  end

  # If the current users type is a studio owner, redirect to the appropriate page.
  def check_user_type
    # if current_studio_owner
    #   redirect_to studio_owners_dashboard_path
    # end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/home.html.erb
<div>

  <h1>Dashboard#home</h1>
  <p>Find me in app/views/dashboard/home.html.erb</p>

  <!--<h4>The old way</h4>-->
<%# if current_user %>
  <%#= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
  <%#= link_to "Edit registration", edit_user_registration_path %>
<%# else %>
  <%#= link_to "Sign up", new_user_registration_path %>
  <%#= link_to "Sign in", new_user_session_path %>
<%# end %>


  <h3>What you might have seen lately</h3>

  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
    <%= link_to "Edit registration", edit_user_registration_path %>
  <% elsif !studio_owner_signed_in? %>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>

  <h3>Admin Links</h3>

  <% if studio_owner_signed_in? %>
    <%= link_to "Sign out", destroy_studio_owner_session_path, method: :delete, data: { turbo_method: :delete } %>
    <%= link_to "Edit registration", edit_studio_owner_registration_path %>
  <% elsif !user_signed_in? %>
    <%= link_to "Sign up", new_studio_owner_registration_path %>
    <%= link_to "Sign in", new_studio_owner_session_path %>
  <% end %>

<!--  <h4>Page Links</h4>-->
  <%#= link_to "Home", root_path %>
  <%#= link_to "Users Path", dashboard_users_path %>
  <%#= link_to "Admin Path", studio_owners_dashboard_path %>


</div>

app/views/dashboard/studio_owners.html.erb
<h1>Dashboard#studio_owners</h1>
<p>Find me in app/views/dashboard/admin.html.erb</p>

<% if current_studio_owner.studio %>
  <%= current_studio_owner.studio.name %>
<% end %>

<% if studio_owner_signed_in? %>
  <%= link_to "Sign out", destroy_studio_owner_session_path, method: :delete, data: { turbo_method: :delete } %>
  <%= link_to "Edit registration", edit_studio_owner_registration_path %>
<% end %>

app/views/dashboard/users.html.erb
<h1>Dashboard#users</h1>
<p>Find me in app/views/dashboard/users.html.erb</p>