config/routes.rb
Rails.application.routes.draw do
  get 'request_payments/index'
  get 'request_payments/new'
  get 'messages/index'
  get 'messages/show'
  devise_for :studio_owners, controllers: {
    sessions: 'studio_owners/sessions'
  }

  # Can add registrations: 'admin/registrations'
  #
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'dashboard#home'

  namespace :users do
    root 'users#dashboard'


  end

  namespace :studio_owners do
    root 'studio_owners#dashboard'
    get 'dashboard', to: 'studio_owners#dashboard'
    resources :student_management, only: [:index]
    resources :request_payments, only: [:index, :new]
    resource :account_management, only: [:edit, :index], controller: 'account_management' do
      post :accept_tos, on: :collection
    end
  end

  post '/create-checkout-session', to:'payments#payment_request' do
    content_type 'application/json'
  end

  get '/payment_success', to:'payments#success'
  get '/payment_failure', to:'payments#failure'




  # get 'users/signup', to: 'users/users#signup'
  post 'send_invitation', to: 'invitations#send_invitation'

  # get 'users/dashboard', to: 'users#dashboard', as: 'users_dashboard'
  # get 'studio_owners/dashboard', to: 'studio_owners#dashboard', as: 'studio_owners_dashboard'

  resources :studios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/studio_owner.rb
class StudioOwner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :studio

  after_save :create_stripe_account

  #
  def create
  end

  def create_stripe_account
    # Set Stripe API key (better to move this to an initializer or use environment variable)
    Stripe.api_key = ENV["STRIPE_TEST_KEY"]

    begin
      response = Stripe::Account.create({
                                          type: 'custom',
                                          country: 'US',
                                          email: self.email, # Use 'self' to refer to the email of the StudioOwner instance
                                          capabilities: {
                                            card_payments: { requested: true },
                                            transfers: { requested: true },
                                          },
                                        })

      self.update_column(:stripe_account_id, response.id)

    rescue Stripe::StripeError => e

      Rails.logger.error "Stripe error while creating account: #{e.message}"
    end

  end

  def confirm_stripe_tos
      Stripe.api_key =  ENV['STRIPE_TEST_KEY']

      response = Stripe::Account.update(
        self.stripe_account_id,
        {
          tos_acceptance: {
            date: 1609798905,
            ip: '8.8.8.8',
          },
        },
      )



  end

end

app/controllers/studio_owners/account_management_controller.rb
module StudioOwners
  class AccountManagementController < ApplicationController

    def edit
      # this worked, just didn not show in logs.... work on later
      # current_studio_owner.confirm_stripe_tos
    end

    def index
    end

    def accept_tos
      Rails.logger.info "Accept TOS action called"
      current_studio_owner.confirm_stripe_tos
    end

  end
end

app/controllers/studio_owners/confirmations_controller.rb
# frozen_string_literal: true

class StudioOwners::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/studio_owners/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class StudioOwners::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/studio_owners/passwords_controller.rb
# frozen_string_literal: true

class StudioOwners::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/studio_owners/registrations_controller.rb
# frozen_string_literal: true

class StudioOwners::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
    @studio_owner = true
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the users wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/studio_owners/request_payments_controller.rb
module StudioOwners

  class RequestPaymentsController < ApplicationController

    def index
    end

    def new
    end

  end

end

app/controllers/studio_owners/sessions_controller.rb
# frozen_string_literal: true

class StudioOwners::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/studio_owners/student_management_controller.rb
module StudioOwners

  class StudentManagementController < ApplicationController

    def index
      @students = User.where(studio_id: current_studio_owner.studio.id)
    end
  end

end

app/controllers/studio_owners/studio_owners_controller.rb
module StudioOwners
  class StudioOwnersController < ApplicationController
    before_action :check_studio

    def index

    end

    def dashboard
      @students = User.where(studio_id: current_studio_owner.studio.id)
      @link = make_stripe_link
    end

    def make_stripe_link
      # Set your secret key. Remember to switch to your live secret key in production.
      # See your keys here: https://dashboard.stripe.com/apikeys
      Stripe.api_key = ENV["STRIPE_TEST_KEY"]

      response = Stripe::AccountLink.create({
                                   account: current_studio_owner.stripe_account_id,
                                   refresh_url: 'https://example.com/reauth',
                                   return_url: 'https://example.com/return',
                                   type: 'account_onboarding',
                                 })

      response.url
    end

    def check_studio
      puts 'hello'
      unless current_studio_owner.studio
        # Redirect to the studio creation path
        # Replace 'new_studio_path' with the correct path for your application
        redirect_to new_studio_path
      end
      # No need for an 'if' block since you're only handling the case where the studio does not exist
    end

  end
end

app/controllers/studio_owners/unlocks_controller.rb
# frozen_string_literal: true

class StudioOwners::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/student_management_helper.rb
module StudentManagementHelper
end

app/helpers/studio_owner_helper.rb
module StudioOwnerHelper
end

app/views/studio_owners/student_management/_new_student_modal.erb
<div data-controller="add-student-modal"
     data-action="click->add-student-modal#clickOutside"
     data-add-student-modal-studio-id-value="<%= current_studio_owner.studio.id %>">
  <button  data-action="click->add-student-modal#open" type="button" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Add Student</button>
  <dialog data-add-student-modal-target="modal" class="backdrop:bg-slate-600 backdrop:opacity-80">
    <form method="dialog">
      <div class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">
        <!--
          Background backdrop, show/hide based on modal state.

          Entering: "ease-out duration-300"
            From: "opacity-0"
            To: "opacity-100"
          Leaving: "ease-in duration-200"
            From: "opacity-100"
            To: "opacity-0"
        -->
        <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>

        <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
          <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
            <!--
              Modal panel, show/hide based on modal state.

              Entering: "ease-out duration-300"
                From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                To: "opacity-100 translate-y-0 sm:scale-100"
              Leaving: "ease-in duration-200"
                From: "opacity-100 translate-y-0 sm:scale-100"
                To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            -->
            <div class="relative transform overflow-hidden rounded-lg bg-white px-4 pb-4 pt-5 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg sm:p-6">

              <div>
                <label for="email" class="block text-sm font-medium leading-6 text-gray-900">Email</label>
                <div class="mt-2">
                  <input data-add-student-modal-target="email" type="email" name="email" id="email" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" placeholder="you@example.com" required>
                </div>
              </div>

              <div>
                <div class="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-green-100">
                  <svg class="h-6 w-6 text-green-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                  </svg>
                </div>
                <div class="mt-3 text-center sm:mt-5">
                  <h3 class="text-base font-semibold leading-6 text-gray-900" id="modal-title">Payment successful</h3>
                  <div class="mt-2">
                    <p class="text-sm text-gray-500">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius aliquam laudantium explicabo pariatur iste dolorem animi vitae error totam. At sapiente aliquam accusamus facere veritatis.</p>
                  </div>
                </div>
              </div>
              <div class="mt-5 sm:mt-6 sm:grid sm:grid-flow-row-dense sm:grid-cols-2 sm:gap-3">
                <button data-action="click->add-student-modal#submit" type="button" class="mt-3 inline-flex w-full justify-center rounded-md bg-green-300 px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-green-400 sm:col-start-1 sm:mt-0">Submit</button>
                <button data-action="click->add-student-modal#closeModal"  type="button" class="inline-flex w-full justify-center rounded-md bg-red-400 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 sm:col-start-2">Cancel</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </dialog>
</div>

app/views/studio_owners/student_management/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Users</h1>
      <p class="mt-2 text-sm text-gray-700">A list of all the users in your account including their name, title, email and role.</p>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <%= render('studio_owners/student_management/new_student_modal') %>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Title</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Role</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
            <% @students.each do |student| %>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">Placeholder</td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">Placeholder</td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= student.email %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">Placeholder</td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <a href="#" class="text-indigo-600 hover:text-indigo-900">Edit<span class="sr-only">, Lindsay Walton</span></a>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>



<%= form_with url: create_checkout_session_path, method: :post do %>
  <%= submit_tag "Pay Now" %>
<% end %>