config/routes.rb
Rails.application.routes.draw do
  get 'request_payments/index'
  get 'request_payments/new'
  get 'messages/index'
  get 'messages/show'
  devise_for :studio_owners, controllers: {
    sessions: 'studio_owners/sessions'
  }

  # Can add registrations: 'admin/registrations'
  #
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'dashboard#home'

  namespace :users do
    root 'users#dashboard'


  end

  namespace :studio_owners do
    root 'studio_owners#dashboard'
    get 'dashboard', to: 'studio_owners#dashboard'
    resources :student_management, only: [:index]
    resources :request_payments, only: [:index, :new]
    resource :account_management, only: [:edit, :index], controller: 'account_management' do
      post :accept_tos, on: :collection
    end
  end

  post '/create-checkout-session', to:'payments#payment_request' do
    content_type 'application/json'
  end

  get '/payment_success', to:'payments#success'
  get '/payment_failure', to:'payments#failure'




  # get 'users/signup', to: 'users/users#signup'
  post 'send_invitation', to: 'invitations#send_invitation'

  # get 'users/dashboard', to: 'users#dashboard', as: 'users_dashboard'
  # get 'studio_owners/dashboard', to: 'studio_owners#dashboard', as: 'studio_owners_dashboard'

  resources :studios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_nav_bar.erb
<ul class="flex flex-col space-y-4">
  <%= link_to 'Dashboard', root_path %>
  <li>Invoices</li>
  <%= link_to 'Messages', messages_index_path %>

  <% if current_studio_owner %>

    <%= link_to 'Student Management', studio_owners_student_management_index_path %>
    <li>Request Payment</li>
    <li>Recurring Billing</li>
    <%= link_to "Account Management", edit_studio_owners_account_management_path %>

  <% end %>
</ul>