config/routes.rb
Rails.application.routes.draw do
  get 'request_payments/index'
  get 'request_payments/new'
  get 'messages/index'
  get 'messages/show'
  devise_for :studio_owners, controllers: {
    sessions: 'studio_owners/sessions'
  }

  # Can add registrations: 'admin/registrations'
  #
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'dashboard#home'

  namespace :users do
    root 'users#dashboard'


  end

  namespace :studio_owners do
    root 'studio_owners#dashboard'
    get 'dashboard', to: 'studio_owners#dashboard'
    resources :student_management, only: [:index]
    resources :request_payments, only: [:index, :new]
    resource :account_management, only: [:edit, :index], controller: 'account_management' do
      post :accept_tos, on: :collection
    end
  end

  post '/create-checkout-session', to:'payments#payment_request' do
    content_type 'application/json'
  end

  get '/payment_success', to:'payments#success'
  get '/payment_failure', to:'payments#failure'




  # get 'users/signup', to: 'users/users#signup'
  post 'send_invitation', to: 'invitations#send_invitation'

  # get 'users/dashboard', to: 'users#dashboard', as: 'users_dashboard'
  # get 'studio_owners/dashboard', to: 'studio_owners#dashboard', as: 'studio_owners_dashboard'

  resources :studios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/studio.rb
class Studio < ApplicationRecord
  belongs_to :studio_owner
  has_many :users
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :set_studio, only: %i[ show edit update destroy ]

  # GET /studios or /studios.json
  def index
    @studios = Studio.all
  end

  # GET /studios/1 or /studios/1.json
  def show
  end

  # GET /studios/new
  def new
    @studio = Studio.new
  end

  # GET /studios/1/edit
  def edit
  end

  # POST /studios or /studios.json
  def create
    @studio = Studio.new(studio_params)
    @studio.studio_owner_id = current_studio_owner.id

    respond_to do |format|
      if @studio.save
        format.html { redirect_to studio_url(@studio), notice: "Studio was successfully created." }
        format.json { render :show, status: :created, location: @studio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studios/1 or /studios/1.json
  def update
    respond_to do |format|
      if @studio.update(studio_params)
        format.html { redirect_to studio_url(@studio), notice: "Studio was successfully updated." }
        format.json { render :show, status: :ok, location: @studio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studios/1 or /studios/1.json
  def destroy
    @studio.destroy

    respond_to do |format|
      format.html { redirect_to studios_url, notice: "Studio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studio
      @studio = Studio.find(params[:id])
    end

  def studio_params
    params.require(:studio).permit(:name, :description)
  end

end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/views/studios/_form.html.erb
<%= form_with(model: @studio, local:true) do |form| %>
  <% if studio.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(studio.errors.count, "error") %> prohibited this studio from being saved:</h2>

      <ul>
        <% studio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name, id: :studio_name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description, id: :studio_description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/studios/_studio.html.erb
<div id="<%= dom_id studio %>">
</div>

app/views/studios/edit.html.erb
<h1>Editing studio</h1>

<%= render "form", studio: @studio %>

<br>

<div>
  <%= link_to "Show this studio", @studio %> |
  <%= link_to "Back to studios", studios_path %>
</div>

app/views/studios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Studios</h1>

<div id="studios">
  <% @studios.each do |studio| %>
    <%= render studio %>
    <p>
      <%= link_to "Show this studio", studio %>
    </p>
  <% end %>
</div>

<%= link_to "New studio", new_studio_path %>

app/views/studios/new.html.erb
<h1>New studio</h1>

<%= render "form", studio: @studio %>

<br>

<div>
  <%= link_to "Back to studios", studios_path %>
</div>

app/views/studios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @studio %>

<div>
  <%= link_to "Edit this studio", edit_studio_path(@studio) %> |
  <%= link_to "Back to studios", studios_path %>

  <%= button_to "Destroy this studio", @studio, method: :delete %>
</div>